# Preparation

### Imports

In [19]:
import pandas as pd
import os

#### Users

In [20]:
users_raw_df=pd.DataFrame(pd.read_csv('01Raw/usersRaw.csv'))
users_raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   userId       300 non-null    int64
 1   userName     300 non-null    object
 2   email        300 non-null    object
 3   password     300 non-null    object
 4   role         300 non-null    object
 5   designation  300 non-null    object
 6   gender       300 non-null    object
 7   joinDate     300 non-null    object
dtypes: int64(1), object(7)
memory usage: 18.9+ KB

In [21]:
users_raw_df.drop('password',axis=1,inplace=True)
users_raw_df.drop('gender',axis=1,inplace=True)
users_raw_df.drop('email',axis=1,inplace=True)
users_raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   userId       300 non-null    int64
 1   userName     300 non-null    object
 2   role         300 non-null    object
 3   designation  300 non-null    object
 4   joinDate     300 non-null    object
dtypes: int64(1), object(4)
memory usage: 11.8+ KB

In [22]:
users_raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   userId       300 non-null    int64
 1   userName     300 non-null    object
 2   role         300 non-null    object
 3   designation  300 non-null    object
 4   joinDate     300 non-null    object
dtypes: int64(1), object(4)
memory usage: 11.8+ KB

In [23]:
print(users_raw_df['joinDate'].dtype)
users_raw_df['joinDate']=pd.to_datetime(users_raw_df['joinDate'])
print(users_raw_df['joinDate'].dtype)
users_raw_df.info()

object
datetime64[ns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   userId       300 non-null    int64
 1   userName     300 non-null    object
 2   role         300 non-null    object
 3   designation  300 non-null    object
 4   joinDate     300 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 11.8+ KB

In [24]:
users_raw_df

     userId             userName      role    designation   joinDate
0         1          Brian Davis  Employee  Designation 5 2024-03-29
1         2     Marsha Wilderman  Employee  Designation 9 2024-06-13
2         3  Noah Bogisich-Hauck  Employee  Designation 5 2024-10-09
3         4        Bryant Parker  Employee  Designation 5 2024-02-08
4         5       Cecilia Lehner  Employee  Designation 6 2024-01-18
..      ...                  ...       ...            ...        ...
295     296    Scott McKenzie IV  Employee  Designation 7 2024-05-10
296     297     Desiree Swift IV  Employee  Designation 2 2024-04-08
297     298           Hugh Kulas  Employee  Designation 6 2024-09-03
298     299  Fernando Morissette  Employee  Designation 8 2024-05-11
299     300         Timmy Casper  Employee  Designation 9 2023-11-23

[300 rows x 5 columns]

#### Trainings

In [25]:
trainings_raw_df=pd.DataFrame(pd.read_csv('01Raw/trainingsRaw.csv'))
trainings_raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   trainingId    100 non-null    int64
 1   trainingName  100 non-null    object
 2   description   100 non-null    object
 3   domainName    100 non-null    object
 4   domainId      100 non-null    int64
 5   duration      100 non-null    int64
 6   startDate     100 non-null    object
dtypes: int64(3), object(4)
memory usage: 5.6+ KB

In [26]:
def assignDomainId(domainName):
    if domainName == 'DataEngineering':
        return 1
    elif domainName == 'FullStack':
        return 2
    elif domainName == 'DevOps':
        return 3
    elif domainName == 'DataScience':
        return 4
    elif domainName =='SoftSkills':
        return 5


trainings_raw_df['domainId'] = trainings_raw_df['domainName'].apply(assignDomainId)

In [27]:
trainings_raw_df.info()
trainings_raw_df.drop('description',axis=1,inplace=True)
trainings_raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   trainingId    100 non-null    int64
 1   trainingName  100 non-null    object
 2   description   100 non-null    object
 3   domainName    100 non-null    object
 4   domainId      100 non-null    int64
 5   duration      100 non-null    int64
 6   startDate     100 non-null    object
dtypes: int64(3), object(4)
memory usage: 5.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   trainingId    100 non-null    int64
 1   trainingName  100 non-null    object
 2   domainName    100 non-null    object
 3   domainId      100 non-null    int64
 4   duration      100 non-null    int64
 5   startDate     100 non-null    object
dtypes: int64(3), object(3)
memory usage: 4.8+ KB

In [28]:
trainings_raw_df['startDate']=pd.to_datetime(trainings_raw_df['startDate'])
trainings_raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   trainingId    100 non-null    int64
 1   trainingName  100 non-null    object
 2   domainName    100 non-null    object
 3   domainId      100 non-null    int64
 4   duration      100 non-null    int64
 5   startDate     100 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 4.8+ KB

#### Responses

responses_raw_df=pd.DataFrame(pd.read_csv('01Raw/responsesRaw.csv'))
responses_raw_df['userId'].nunique()

In [29]:
responses_raw_df=pd.DataFrame(pd.read_csv('01Raw/responsesRaw.csv'))
responses_raw_df['userId'].nunique()

300

In [30]:
responses_raw_df['responseDate']=pd.to_datetime(responses_raw_df['responseDate'])
print(responses_raw_df['responseDate'].dtypes)
responses_raw_df.info()

datetime64[ns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   responseId    10000 non-null  int64
 1   userId        10000 non-null  int64
 2   trainingId    10000 non-null  int64
 3   score         10000 non-null  int64
 4   responseDate  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4)
memory usage: 390.8 KB

#### Organisation Review

organisation_reviews_raw_df=pd.DataFrame(pd.read_csv('01Raw/organisationReviewsRaw.csv'))
organisation_reviews_raw_df.info()

In [31]:
organisation_reviews_raw_df=pd.DataFrame(pd.read_csv('01Raw/organisationReviewsRaw.csv'))
organisation_reviews_raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   reviewId           10000 non-null  int64
 1   userId             10000 non-null  int64
 2   trainingId         10000 non-null  int64
 3   organisationScore  10000 non-null  int64
 4   discipline         10000 non-null  bool
 5   hardWorking        10000 non-null  bool
 6   communication      10000 non-null  bool
dtypes: bool(3), int64(4)
memory usage: 341.9 KB

In [32]:
def valueChange(values):
    if values == True:
        return 1
    elif values== False:
        return 0
    
organisation_reviews_raw_df['communicationMarks']=organisation_reviews_raw_df['communication'].apply(valueChange)
organisation_reviews_raw_df['hardWorkingMarks']=organisation_reviews_raw_df['hardWorking'].apply(valueChange)
organisation_reviews_raw_df['disciplineMarks']=organisation_reviews_raw_df['discipline'].apply(valueChange)
organisation_reviews_raw_df.head()

,reviewId,userId,trainingId,organisationScore,discipline,hardWorking,communication,communicationMarks,hardWorkingMarks,disciplineMarks
0,1,190,79,85,True,False,True,1,0,1
1,2,77,12,68,True,False,True,1,0,1
2,3,72,61,25,True,False,False,0,0,1
3,4,181,21,85,True,False,False,0,0,1
4,5,168,69,28,True,True,False,0,1,1

In [33]:
organisation_reviews_raw_df.drop(columns=['discipline','hardWorking','communication'], inplace=True )
organisation_reviews_raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   reviewId            10000 non-null  int64
 1   userId              10000 non-null  int64
 2   trainingId          10000 non-null  int64
 3   organisationScore   10000 non-null  int64
 4   communicationMarks  10000 non-null  int64
 5   hardWorkingMarks    10000 non-null  int64
 6   disciplineMarks     10000 non-null  int64
dtypes: int64(7)
memory usage: 547.0 KB

#### Loading Data

In [34]:
os.makedirs('02Prep',exist_ok=True)

In [35]:
users_raw_df.to_csv('02Prep/usersPrep.csv', index=False)
trainings_raw_df.to_csv('02Prep/trainingsPrep.csv',index=False)
responses_raw_df.to_csv('02Prep/responsesPrep.csv',index=False)
organisation_reviews_raw_df.to_csv('02Prep/organisationReviewPrep.csv',index=False)